version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas.bitcoin-studio.com
  #gateway: https://openfaas.rogue-paprika.top
  #gateway: https://openfaas-ingress-janaka-steph.cloud.okteto.net
  #gateway: http://127.0.0.1:8080

functions:
  csp-report:
    lang: golang-middleware
    handler: ./function
    image: janakasteph/csp-report:${DEV:-latest}
    #image: registry.cloud.okteto.net/janaka-steph/csp-report